[package]
name = "diecast-commonmark"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
typemap = "*"
pulldown-cmark = "*"

[dependencies.diecast]
path = "../diecast"
